<?php
// Modules/Course/app/Services/Implementations/CourseApiService.php

namespace Modules\Course\Services\Implementations;

use Modules\Course\Services\CourseApiServiceInterface;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Modules\Course\App\Models\Course;
use Modules\Subject\App\Models\Subject;
use Modules\Users\User\App\Models\User;

class CourseApiService implements CourseApiServiceInterface
    {
        public function getAllCourses(): array
        {
            $courses = Course::with(['subjects', 'students'])
                ->withCount(['subjects', 'students'])
                ->orderBy('id', 'asc')
                ->get()
                ->map(function ($course) {
                    return $this->transformCourse($course);
                })
                ->toArray();

            return [
                'total_count' => count($courses),
                'courses' => $courses
            ];
        }

        public function getCourseByUuid(string $uuid): ?Course
        {
        $course = Course::with(['subjects', 'students'])
            ->withCount(['subjects', 'students'])
            ->where('uuid', $uuid)
            ->first();

        return $course ? $course : null;
    }

    public function createCourse(array $data): Course
    {
        return DB::transaction(function () use ($data) {
            // UUID will be auto-generated by the model's boot method
            // Ensure UUID is set as string
            if (!isset($data['uuid'])) {
                $data['uuid'] = (string) Str::uuid();
            } else {
                $data['uuid'] = (string) $data['uuid'];
            }

            $course = Course::create($data);
            return $course->load(['subjects', 'students']);
        });
    }

    public function updateCourse(string $uuid, array $data): Course
    {
        return DB::transaction(function () use ($uuid, $data) {
            $course = Course::where('uuid', $uuid)->firstOrFail();
            $course->update($data);
            return $course->fresh(['subjects', 'students']);
        });
    }

    public function deleteCourse(string $uuid): bool
    {
        return DB::transaction(function () use ($uuid) {
            $course = Course::where('uuid', $uuid)->firstOrFail();

            // Detach all students and subjects
            $course->students()->detach();
            $course->subjects()->detach();

            return $course->delete();
        });
    }

    public function getCoursesPaginated(int $perPage = 10): array
    {
        $courses = Course::with(['subjects', 'students'])
            ->withCount(['subjects', 'students'])
            ->orderBy('id', 'asc')
            ->get()
            ->map(function ($course) {
                return $this->transformCourse($course);
            })
            ->toArray();

        return [
            'total_count' => count($courses),
            'courses' => $courses
        ];
    }

    public function getCoursesWithSubjects(string $courseUuid): array
    {
        $course = Course::with(['subjects' => function ($query) {
            // Explicitly select subject fields including uuid
            $query->select('subjects.id', 'subjects.uuid', 'subjects.subject_name', 'subjects.subject_code', 'subjects.class_level', 'subjects.status')
                  ->orderBy('subject_name', 'asc');
        }])->withCount('subjects')->where('uuid', $courseUuid)->firstOrFail();

        return [
            'course' => $this->transformCourse($course),
            'subjects_count' => $course->subjects_count,
            'subjects' => $course->subjects->map(function ($subject) {
                return [
                    'uuid' => $subject->uuid,
                    'id' => $subject->id,
                    'subject_code' => $subject->subject_code,
                    'subject_name' => $subject->subject_name,
                    'class_level' => $subject->class_level,
                    'status' => $subject->status,
                    'assigned_at' => $subject->pivot->created_at ?? null
                ];
            })->toArray()
        ];
    }

    public function assignSubjectsToCourse(string $courseUuid, array $subjectIds): array
    {
        return DB::transaction(function () use ($courseUuid, $subjectIds) {
            $course = Course::where('uuid', $courseUuid)->firstOrFail();

            // Validate that all subject IDs exist
            $existingSubjects = Subject::whereIn('id', $subjectIds)->pluck('id')->toArray();
            $nonExistingSubjects = array_diff($subjectIds, $existingSubjects);

            if (!empty($nonExistingSubjects)) {
                throw new \Exception('One or more subject IDs do not exist: ' . implode(', ', $nonExistingSubjects));
            }

            // Sync subjects - this replaces existing subjects with the new ones
            $course->subjects()->sync($subjectIds);

            // Return updated course with all its subjects
            return $this->getCoursesWithSubjects($courseUuid);
        });
    }

    public function addSubjectToCourse(string $courseUuid, int $subjectId): array
    {
        return DB::transaction(function () use ($courseUuid, $subjectId) {
            $course = Course::where('uuid', $courseUuid)->firstOrFail();
            $subject = Subject::findOrFail($subjectId);

            if ($course->hasSubject($subjectId)) {
                throw new \Exception('Subject is already assigned to this course.');
            }

            $course->subjects()->attach($subjectId);

            return $this->getCoursesWithSubjects($courseUuid);
        });
    }

    public function removeSubjectFromCourse(string $courseUuid, int $subjectId): array
    {
        return DB::transaction(function () use ($courseUuid, $subjectId) {
            $course = Course::where('uuid', $courseUuid)->firstOrFail();

            if (!$course->hasSubject($subjectId)) {
                throw new \Exception('Subject is not assigned to this course.');
            }

            $course->subjects()->detach($subjectId);

            return $this->getCoursesWithSubjects($courseUuid);
        });
    }

    // Student course methods
    public function enrollStudent(string $courseUuid, string $studentUuid): array
    {
        return DB::transaction(function () use ($courseUuid, $studentUuid) {
            $course = Course::where('uuid', $courseUuid)->firstOrFail();
            $student = User::where('uuid', $studentUuid)->firstOrFail();

            if ($course->hasStudent($student->id)) {
                throw new \Exception('Student is already enrolled in this course.');
            }

            $course->enrollStudent($student->id, 'active');

            return [
                'message' => 'Student enrolled successfully',
                'course' => $this->transformCourse($course->fresh(['students'])),
                'student' => [
                    'uuid' => $student->uuid,
                    'name' => $student->name,
                    'email' => $student->email
                ]
            ];
        });
    }

    public function removeStudent(string $courseUuid, string $studentUuid): bool
    {
        return DB::transaction(function () use ($courseUuid, $studentUuid) {
            $course = Course::where('uuid', $courseUuid)->firstOrFail();
            $student = User::where('uuid', $studentUuid)->firstOrFail();

            if (!$course->hasStudent($student->id)) {
                throw new \Exception('Student is not enrolled in this course.');
            }

            $course->removeStudent($student->id);

            return true;
        });
    }

    public function updateStudentStatus(string $courseUuid, string $studentUuid, string $status): array
    {
        return DB::transaction(function () use ($courseUuid, $studentUuid, $status) {
            $course = Course::where('uuid', $courseUuid)->firstOrFail();
            $student = User::where('uuid', $studentUuid)->firstOrFail();

            if (!$course->hasStudent($student->id)) {
                throw new \Exception('Student is not enrolled in this course.');
            }

            $validStatuses = ['active', 'dropped', 'completed'];
            if (!in_array($status, $validStatuses)) {
                throw new \Exception('Invalid status. Valid statuses: ' . implode(', ', $validStatuses));
            }

            $course->updateStudentStatus($student->id, $status);

            return [
                'message' => 'Student status updated successfully',
                'student_uuid' => $student->uuid,
                'status' => $status
            ];
        });
    }

    public function getEnrolledStudents(string $courseUuid, int $perPage = 10): array
    {
        $course = Course::where('uuid', $courseUuid)->firstOrFail();

        $students = $course->students()
            ->orderBy('id', 'asc')
            ->get()
            ->map(function ($student) {
                return [
                    'uuid' => $student->uuid,
                    'name' => $student->name,
                    'email' => $student->email,
                    'phone_no' => $student->phone_no,
                    'enrollment_date' => $student->pivot->enrollment_date,
                    'status' => $student->pivot->status
                ];
            })->toArray();

        return [
            'total_count' => count($students),
            'students' => $students
        ];
    }

    public function getStudentCourses(string $studentUuid, int $perPage = 10): array
    {
        $student = User::where('uuid', $studentUuid)->firstOrFail();

        $courses = $student->enrolledCourses()
            ->with(['subjects'])
            ->withCount('students')
            ->orderBy('id', 'asc')
            ->get()
            ->map(function ($course) {
                return $this->transformCourse($course);
            })->toArray();

        return [
            'total_count' => count($courses),
            'courses' => $courses
        ];
    }

    public function isStudentEnrolled(string $courseUuid, string $studentUuid): bool
    {
        $course = Course::where('uuid', $courseUuid)->firstOrFail();
        $student = User::where('uuid', $studentUuid)->firstOrFail();

        return $course->hasStudent($student->id);
    }

    private function transformCourse(Course $course): array
    {
        return [
            'uuid' => $course->uuid,
            'id' => $course->id,
            'course_name' => $course->course_name,
            'description' => $course->description,
            'category' => $course->category,
            'subjects_count' => $course->subjects_count ?? $course->subjects()->count(),
            'students_count' => $course->students_count ?? $course->students()->count(),
            'created_at' => $course->created_at,
            'updated_at' => $course->updated_at,
        ];
    }
}
